sudo: false
language: rust
rust: stable

os:
  - linux

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script: |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
  cd practice &&
  travis-cargo build &&
  travis-cargo test